---

version: '3.8'

services:
  web:
    image: wordpress:5.8.2-apache
    container_name: skinorea_web
    environment:
      SERVERNAME: skinorea.local
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: local_skinorea
      WORDPRESS_DB_USER: local_skinorea
      WORDPRESS_DB_PASSWORD: local_skinorea
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: skinorea_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=local_skinorea
      - MYSQL_USER=local_skinorea
      - MYSQL_PASSWORD=local_skinorea
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.1
    container_name: skinorea_adminer
    ports:
      - 8080:8080
